services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: monapp
      POSTGRES_PASSWORD: monapp
      POSTGRES_DB: monapp
    ports:
      - "5432:5432"
    volumes:
      - monapp-db-data:/var/lib/postgresql/data

volumes:
  monapp-db-data:
